# Use Ubuntu 22.04 as base image
FROM gmao/llvm-flang

# Set environment variables
ENV DEBIAN_FRONTEND=noninteractive

# Install necessary packages
RUN apt-get update && apt-get install -y \
    software-properties-common \
    wget \
    bzip2 \
    libz-dev \
    g++ \
    ca-certificates \
    curl \
    git \
    nano \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

RUN add-apt-repository ppa:ubuntu-toolchain-r/test \
    && apt-get install -y gfortran-14

# Set up working directory
WORKDIR /packages

# Install Anaconda
RUN wget https://repo.anaconda.com/archive/Anaconda3-2024.10-1-Linux-x86_64.sh -O /tmp/anaconda.sh \
    && bash /tmp/anaconda.sh -b -p /opt/anaconda \
    && rm /tmp/anaconda.sh

# Add Anaconda to PATH
ENV PATH="/opt/anaconda/bin:${PATH}"

# Initialize conda for bash shell
RUN echo ". /opt/anaconda/etc/profile.d/conda.sh" >> ~/.bash_profile
RUN echo ". /opt/anaconda/etc/profile.d/conda.sh" >> ~/.bashrc

# Copy environment.yaml file
COPY NR_Fano_dan_env.yaml .

# Create conda environment from the yaml file
# this installs fpm and intel compiler
RUN conda env create -f NR_Fano_dan_env.yaml
RUN echo "conda activate NR_Fano" >> ~/.bash_profile
RUN echo "conda activate NR_Fano" >> ~/.bashrc

# Source - https://stackoverflow.com/a/39777387
# Posted by Ahmad Abdelghany, modified by community. See post 'Timeline' for change history
# Retrieved 2025-11-09, License - CC BY-SA 4.0
# this command, together with putting conda activation in .bash_profile, means we have
# enabled the conda environment for every command
SHELL ["/bin/bash", "--login", "-c"] 

# Check out TAU
RUN git clone https://github.com/UO-OACISS/tau2.git --depth=1

# Build TAU
# -pthread to enable pthread
# Don’t specify -mpi to build without MPI
# Most builds of TAU should use bfd, unwind, dwarf, otf to support sampling and tracing
#RUN cd tau2 \
#    && ./configure -cc=gcc -c++=g++ -fortran=gfortran -bfd=download -unwind=download -dwarf=download -otf=download -pthread \
#    && make -j install


WORKDIR /app

# Copy the fortran code over
# first we build the expected directory structure
# and then we copy files
RUN mkdir /app/src
RUN mkdir /app/test

COPY src /app/src/
COPY test /app/test
COPY fpm.toml /app/

# also copy over the python functions for testing
RUN mkdir /app/python
COPY python /app/python/
COPY *.py /app

# Now compile the fortran code
RUN fpm test --compiler flang-new --profile release --flag -O3 \
    && fpm install --prefix=.  --compiler flang-new --profile release --flag -O3

