# Nix builder
FROM nixos/nix

RUN nix-channel --update

RUN nix-env -iA nixpkgs.gfortran15 nixpkgs.vim

# Set up working directory
WORKDIR /app

# Install fpm from source
# There is an fpm-fortran nix package but it's version 0.11.0
RUN git clone https://github.com/fortran-lang/fpm
RUN cd fpm \
    && ./install.sh

RUN echo "alias fpm=~/.local/bin/fpm" >> ~/.bash_profile
RUN echo "alias fpm=~/.local/bin/fpm" >> ~/.bashrc

# Copy nix shell file
COPY shell.nix .

# Build the python environment defined in shell.nix
RUN nix-shell

# Copy the fortran code over
# first we build the expected directory structure
# and then we copy files
RUN mkdir /app/src
RUN mkdir /app/test

COPY src /app/src/
COPY test /app/test
COPY fpm.toml /app/

# also copy over the python functions for testing
RUN mkdir /app/python
COPY python /app/python/
COPY *.py /app

# Now compile the fortran code
RUN ~/.local/bin/fpm test --compiler gfortran --profile release --flag "-march=native -fopenmp -ftree-parallelize-loops=4 -fcoarray=single -fPIC"
RUN ~/.local/bin/fpm install --prefix=. --flag "-march=native -fopenmp -ftree-parallelize-loops=4 -fcoarray=single -fPIC"

# Needed to find the appropriate .so files from within python
ENV LD_LIBRARY_PATH=/app/lib

# Always want to be in the python environment we build with shell.nix
# Idea from https://ropensci.r-universe.dev/articles/rix/z-advanced-topic-using-nix-inside-docker.html
CMD ["nix-shell"]
